# Generated by Django 5.1.1 on 2024-10-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicManagement', '0001_initial'),
    ]

    operations = [
    ]
