# Generated by Django 5.1.1 on 2024-10-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PaymentGateway', '0002_auto_20241016_0915'),
        ('pembayaranSPP', '0003_auto_20241016_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengembalianDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengembalian', models.DateField(null=True)),
                ('jumlah_dikembalikan', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('alasan_pengembalian', models.TextField(null=True)),
                ('id_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentGateway.pembayaran')),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_tagihan', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status_tagihan', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Dibayar')], default='BELUM', max_length=20)),
                ('tanggal_tagihan', models.DateField(auto_now_add=True)),
                ('jatuh_tempo', models.DateField(null=True)),
                ('id_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.mahasiswa')),
                ('id_spp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.spp')),
            ],
        ),
    ]
