# Generated by Django 5.1.1 on 2024-09-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BillingSystem', '0001_initial'),
        ('PaymentGateway', '0001_initial'),
        ('pembayaranSPP', '0002_remove_pembayaran_id_mahasiswa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembaliandana',
            name='id_pembayaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentGateway.pembayaran'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='id_mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.mahasiswa'),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='id_spp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.spp'),
        ),
    ]
