# Generated by Django 5.1.1 on 2024-10-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0002_initial'),
    ]

    operations = [
    ]
