# Generated by Django 5.1.1 on 2024-09-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pembayaranSPP', '0002_remove_pembayaran_id_mahasiswa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField(null=True)),
                ('metode_pembayaran', models.CharField(max_length=20, null=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status_pembayaran', models.CharField(max_length=20, null=True)),
                ('id_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.mahasiswa')),
                ('id_spp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.spp')),
            ],
        ),
        migrations.CreateModel(
            name='Log_transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_log', models.DateField(null=True)),
                ('status_transaksi', models.CharField(max_length=20, null=True)),
                ('id_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentGateway.pembayaran')),
            ],
        ),
    ]
