# Generated by Django 5.1.1 on 2024-10-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentGateway', '0001_initial'),
    ]

    operations = [
    ]
