# Generated by Django 5.1.1 on 2024-09-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_admin', models.CharField(max_length=50, null=True)),
                ('email_admin', models.CharField(max_length=60, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=15, null=True)),
                ('nama', models.CharField(max_length=50, null=True)),
                ('program_studi', models.CharField(max_length=50, null=True)),
                ('angkatan', models.CharField(max_length=20, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_spp', models.CharField(max_length=40, null=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('semester', models.CharField(max_length=20, null=True)),
                ('tahun_akademik', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField(null=True)),
                ('metode_pembayaran', models.CharField(max_length=20, null=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status_pembayaran', models.CharField(max_length=20, null=True)),
                ('id_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.mahasiswa')),
                ('id_spp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.spp')),
            ],
        ),
        migrations.CreateModel(
            name='Log_transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_log', models.DateField(null=True)),
                ('status_transaksi', models.CharField(max_length=20, null=True)),
                ('id_pyaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaranSPP.pembayaran')),
            ],
        ),
    ]
