# Generated by Django 5.1.1 on 2024-09-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaranSPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='id_mahasiswa',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='id_spp',
        ),
        migrations.DeleteModel(
            name='Log_transaksi',
        ),
        migrations.DeleteModel(
            name='Pembayaran',
        ),
    ]
