# Generated by Django 5.1.1 on 2024-10-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaranSPP', '0002_remove_pembayaran_id_mahasiswa_and_more'),
    ]

    operations = [
    ]
